version: '3.8'
x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      RUBY_VERSION: '3.1.3-alpine'
  stdin_open: true
  tty: true
  env_file: .env
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
  environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432
  depends_on:
    - redis
    - postgres

services:
  app:
    <<: *base
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - '3000:3000'
  js:
    <<: *base
    command: yarn build --watch

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'

  sidekiq:
    <<: *base
    command: bundle exec sidekiq

volumes:
  bundle:
  node_modules:
  postgres: