---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/shared/sessions":
    post:
      summary: Creates session
      tags:
      - Sessions
      parameters:
      - name: session
        in: path
        schema:
          type: object
          properties:
            email:
              type: string
        required: true
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: User Email
                  first_name:
                    type: string
                  last_name:
                    type: string
                  full_name:
                    type: string
                  jwt:
                    type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
